-- THIS IS TO CREATE A BTREE INDEX ON THE USER_ID COLUMN OF THE USERS TABLE
CREATE INDEX USER_ID ON users(user_id);
-- THIS IS TO CREATE A FULL TEXT INDEX ON THE CONTENT COLUMN OF THE POSTS TABLE
CREATE FULLTEXT INDEX CONTENT ON posts(content);
-- THIS IS TO CREATE A UNIQUE INDEX ON THE EMAIL COLUMN OF THE USERS TABLE
CREATE UNIQUE INDEX EMAIL ON users(email);
-- NOTE THAT I HAVE CREATED MULTIPLE INDEXES WHEN NECESSARY

